"""add detection.zone column

Revision ID: 09ddcb232ca0
Revises: 5848677a8bef
Create Date: 2026-05-08 17:46:17.154115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ddcb232ca0'
down_revision: Union[str, Sequence[str], None] = '5848677a8bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('zone', sa.String(), server_default='midship', nullable=False))
    op.create_index(op.f('ix_detections_zone'), 'detections', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_zone'), table_name='detections')
    op.drop_column('detections', 'zone')
    # ### end Alembic commands ###
