"""initial schema

Revision ID: 5848677a8bef
Revises: 
Create Date: 2026-05-07 18:12:57.600630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5848677a8bef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inspection_id', sa.String(), nullable=False),
    sa.Column('defect_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('psc_code', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_inspection_id'), 'detections', ['inspection_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('inspector_id', sa.String(), nullable=False),
    sa.Column('port_of_inspection', sa.String(), nullable=False),
    sa.Column('mou_region', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('critical_defects', sa.Integer(), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_vessel_id'), 'inspections', ['vessel_id'], unique=False)
    op.create_table('sync_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('edge_server_id', sa.String(), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_events_vessel_id'), 'sync_events', ['vessel_id'], unique=False)
    op.create_table('vessels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('management_company', sa.String(), nullable=False),
    sa.Column('edge_server_id', sa.String(), nullable=False),
    sa.Column('last_psc_inspection', sa.String(), nullable=True),
    sa.Column('detention_history', sa.JSON(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessels')
    op.drop_index(op.f('ix_sync_events_vessel_id'), table_name='sync_events')
    op.drop_table('sync_events')
    op.drop_index(op.f('ix_inspections_vessel_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_detections_inspection_id'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
